workflows:
  android-workflow:
    name: Android Workflow
    instance_type: linux_x2
    environment:
      groups:
        - default
    scripts:
      - name: Set up environment
        script: |
          echo "Setting up environment..."
          node --version
          npm --version
      - name: Install dependencies
        script: |
          echo "Installing dependencies..."
          npm ci || npm install
      - name: Install global tools
        script: |
          echo "Installing global tools..."
          npm install -g @capacitor/cli
      - name: Sync Capacitor
        script: |
          echo "Syncing Capacitor..."
          npx cap sync android || node ./node_modules/.bin/cap sync android
      - name: Check Android directory
        script: |
          echo "Checking Android directory..."
          ls -la android/
      - name: Build Android
        script: |
          echo "Building Android APK..."
          cd android && chmod +x ./gradlew && ./gradlew assembleDebug --stacktrace
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
