workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    scripts:
      - name: Set up environment
        script: |
          echo "Setting up environment..."
          node --version
          npm --version
      - name: Install dependencies
        script: |
          echo "Installing dependencies..."
          npm install
      - name: Sync Capacitor
        script: |
          echo "Syncing Capacitor..."
          npx cap sync android
      - name: Build Android
        script: |
          echo "Building Android APK..."
          cd android && chmod +x ./gradlew && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
